### ISSUE TITLE
Request for advice on how to update context Tokens after refresh routine

### ISSUE THREAD

**Issue by bangonkali** [tuxiem/AspNetCore-keycloak#6]
Hi! Awesome work on this guide. I'm looking at ASP Net Core 7 version of the project which you added recently. 

How to update the outcome of `await context.GetTokenAsync("access_token")`?

I have sort of middleware similar to below which takes care of renewing tokens if necessary:

```cs
    public async Task InvokeAsync(HttpContext context)
    {
        // if not authenticated then just execute to next middleware and return
        if (context.User.Identity?.IsAuthenticated != true)
        {
            await _next(context);
            return;
        }
        
        // get username, for keycloak you need to regex this to get the clean username
        var currentUserName = context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        
        // logs an error so it's easier to find - thanks debug.
        if (currentUserName != null) _logger.LogInformation($"Current user: {currentUserName}");

        //Debug this line of code if you want to validate the content jwt.io
        var accessToken = await context.GetTokenAsync("access_token");
        var idToken = await context.GetTokenAsync("id_token");
        var refreshToken = await context.GetTokenAsync("refresh_token");
        
        // check if accessToken is expired
        if (IsTokenExpired(accessToken))
        {
            var newAccessToken = await GetRefreshTokenAsync(refreshToken);
            var serviceAccessToken = await GetTokenExchangeAsync(newAccessToken);
            _logger.LogInformation("Access token is expired, refreshing token");

            // how to update the outcome of `await context.GetTokenAsync("access_token")`?
        }
        
        // Call the next delegate/middleware in the pipeline.
        await _next(context);
    }
```

Full code for middleware: https://gist.github.com/bangonkali/f3bf3641653bc41e24dd7560bd2e6c74

You can then apply this on your app using the following:

```cs
app.UseTokenExchange();
```

**Comment by tuxiem** [comment]
Hi,

I'm not sure I follow what you want with that loop, since calling the context gets you a new access_token already.
Just use the 'getrefreshtoken' in tokenexchange.cs to get a new access token returned from the refresh token request, or implement the same in your middleware.

For production scenarios I would definitely look into placing the refresh token as part of the startup.cs - so the dotnet middleware handles it automatically, like Auth0's library does.
But I haven't looked into adding that to this demo repo.
I don't use keycloak or dotnet any longer, so my knowledge on the subject is also limited tbh😊
